version: "3.8"
services:
  www:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html/
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
volumes:
  persistent:
